package com.dante.subjects.config;

import com.crawljax.core.configuration.CrawljaxConfiguration;
import com.crawljax.core.configuration.Form;
import com.crawljax.core.configuration.InputSpecification;
import com.crawljax.core.state.Identification;
import com.crawljax.forms.FormInput;
import com.crawljax.stateabstractions.visual.imagehashes.DHashStateVertexFactory;
import com.dante.subjects.ApplicationNames;
import com.dante.subjects.Config;
import com.dante.suitegenerator.SuiteGeneratorConfig;
import com.dante.tedd.extraction.DependencyGraphExtractionConfig;
import com.dante.utils.Properties;

/**
 * The application phoenix is NON DETERMINISTIC. In particular the order in which the boards are listed in the menu
 * is random. This will break the test suite generated by the crawler unless the application behaviour is changed. For
 * now I changed the generated test suite in order to cope with non determinism.
 * */
public class PhoenixConfig extends Config {

    private static final String url = "http://localhost:4000";
    private static final int waitTimeAfterReload = 1000;

    public PhoenixConfig() {
        super(ApplicationNames.Name.PHOENIX.getName());
    }

    @Override
    public CrawljaxConfiguration.CrawljaxConfigurationBuilder getCrawljaxConfig() {

        System.out.println("PHOENIX_CONFIG_PROFILE=SIGN_IN_ONLY_V1");

        CrawljaxConfiguration.CrawljaxConfigurationBuilder builder =
                this.crawljaxCommonConfig(
                        url,
                        Properties.MAX_RUNTIME,
                        300,
                        waitTimeAfterReload);

        /*
         * FIRED is intentional for this profile.
         *
         * CHECKED marked all candidates on the authenticated My Boards page
         * as consumed after the first "Boards" menu click. The crawler then
         * reached an equivalent state with zero candidates and stopped before
         * clicking "Add new board...".
         *
         * The previous FIRED list loop is controlled separately by using one
         * list input value, scoped click rules and same-form-once handling.
         */
        builder.setConsiderCandidateElementsOnce(
                CrawljaxConfiguration.CandidateElementsMode.fired);

        builder.setStateVertexFactory(new DHashStateVertexFactory());

        /*
         * Do not use RANDOM priority and do not register every A/BUTTON/DIV.
         * Only coverage-relevant business actions from Phoenix.json are
         * registered below.
         */

        // --------------------------------------------------------------
        // Authentication flow: Sign in only
        // --------------------------------------------------------------
        /*
         * Start from the application's default Sign in page and authenticate
         * as the seeded John account. The Sign up branch is disabled so the
         * crawler does not split into two incompatible authenticated sessions.
         */
        builder.crawlRules().click("button")
                .withText("Sign in");

        builder.crawlRules().dontClick("a")
                .withAttribute("href", "/sign_up");
        builder.crawlRules().dontClick("a")
                .withText("Create new account");
        builder.crawlRules().dontClick("button")
                .withText("Sign up");

        // --------------------------------------------------------------
        // Board flows
        // --------------------------------------------------------------
        builder.crawlRules().click("a")
                .withAttribute("id", "add_new_board");
        builder.crawlRules().click("a")
                .underXPath(
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/SECTION[1]/DIV[1]/DIV[1]/DIV[1]");
        builder.crawlRules().click("div")
                .withAttribute("class", "board add-new");

        /*
         * Existing board tiles use class="board"; their child DIV.inner was
         * not reliably matched by the previous scoped XPath rule.
         */
        builder.crawlRules().click("div")
                .withAttribute("class", "board");

        builder.crawlRules().click("button")
                .withText("Create board");
        /*
         * Allow reopening the board selector after a board is created.
         * This gives Crawljax another chance to reach Add new board...
         * and submit the form with the next configured board value.
         */
        builder.crawlRules().click("a")
                .withText("Boards");
        builder.crawlRules().click("a")
                .withText("Add new board...");

        // --------------------------------------------------------------
        // List flows
        // --------------------------------------------------------------
        /*
         * Add at most three lists. The Add-new-list tile moves one column
         * to the right after every successful save, so only the first three
         * positions are registered.
         */
        final String listWrapperXPath =
                "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]"
                        + "/DIV[1]/DIV[1]/DIV[1]";

        builder.crawlRules().click("div")
                .withText("Add new list...")
                .underXPath(listWrapperXPath + "/DIV[1]");
        builder.crawlRules().click("div")
                .withText("Add new list...")
                .underXPath(listWrapperXPath + "/DIV[2]");
        builder.crawlRules().click("div")
                .withText("Add new list...")
                .underXPath(listWrapperXPath + "/DIV[3]");
        builder.crawlRules().click("button")
                .withText("Save list");

        // --------------------------------------------------------------
        // Card flows
        // --------------------------------------------------------------
        /*
         * Create one card in each of the first three lists. The predicate
         * stops the same list from receiving cards repeatedly.
         */
        builder.crawlRules().click("a")
                .withText("Add a new card...")
                .underXPath(
                        listWrapperXPath
                                + "/DIV[1][not(.//DIV[contains(@class, 'card-content')])]");
        builder.crawlRules().click("a")
                .withText("Add a new card...")
                .underXPath(
                        listWrapperXPath
                                + "/DIV[2][not(.//DIV[contains(@class, 'card-content')])]");
        builder.crawlRules().click("a")
                .withText("Add a new card...")
                .underXPath(
                        listWrapperXPath
                                + "/DIV[3][not(.//DIV[contains(@class, 'card-content')])]");
        builder.crawlRules().click("button")
                .withText("Add");
        builder.crawlRules().click("div")
                .withAttribute("class", "card-content");

        // Card modal: edit, comment, tags and members
        builder.crawlRules().click("a")
                .withText("Edit");
        builder.crawlRules().click("button")
                .withText("Save card");
        builder.crawlRules().click("button")
                .withText("Save comment");
        builder.crawlRules().click("a")
                .withText("Members");
        builder.crawlRules().click("a")
                .withText("Tags");

        /*
         * Select concrete member options instead of the selector container.
         * The previous broad XPath could click the wrong anchor or only open
         * the selector without choosing a member.
         */
        builder.crawlRules().click("a")
                .underXPath(
                        "//DIV[contains(@class, 'members-selector')]//LI[1]");
        builder.crawlRules().click("a")
                .underXPath(
                        "//DIV[contains(@class, 'members-selector')]//LI[2]");

        /*
         * Select only two tags and never click a selected tag again.
         *
         * Do not use position-based tag fallbacks here: after selection the
         * same LI remains visible and the fallback clicked it again, producing
         * state20 -> selected -> state20 toggle loops until MAX_TIME.
         */
        builder.crawlRules().click("a")
                .withAttribute("class", "tag green ");
        builder.crawlRules().click("a")
                .withAttribute("class", "tag yellow ");

        /*
         * Do not close or delete the card before Edit, Save comment,
         * Members and Tags have been explored. Both parent anchors and icon
         * children are excluded because Crawljax may select either node.
         */
        builder.crawlRules().dontClick("a")
                .withAttribute("class", "close");
        builder.crawlRules().dontClick("a")
                .withAttribute("class", "delete");
        builder.crawlRules().dontClick("i")
                .withAttribute("class", "fa fa-close");
        builder.crawlRules().dontClick("i")
                .withAttribute("class", "fa fa-trash-o");

        // --------------------------------------------------------------
        // Board member flow disabled for the John Sign-in profile
        // --------------------------------------------------------------
        /*
         * The authenticated user is john@phoenix-trello.com. Submitting the
         * same address through Add member produces the application's self-add
         * error, so the member flow is intentionally excluded from this
         * profile. Board/list/card/modal coverage remains enabled.
         */
        builder.crawlRules().dontClick("button")
                .withText("Add member");

        // --------------------------------------------------------------
        // Low-value/destructive navigation guards
        // --------------------------------------------------------------
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://trello.com");
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://diacode.com");
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://twitter.com/bigardone");

        builder.crawlRules().dontClick("a")
                .withText("Trello");
        builder.crawlRules().dontClick("a")
                .withText("Diacode");
        builder.crawlRules().dontClick("a")
                .withText("@bigardone");
        builder.crawlRules().dontClick("a")
                .withText("Sign out");
        builder.crawlRules().dontClick("a")
                .withAttribute("class", "current-user");
        builder.crawlRules().dontClick("a")
                .underXPath(
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/HEADER[1]");
        builder.crawlRules().dontClick("a")
                .withText("cancel");

        InputSpecification inputSpecification = new InputSpecification();

        /*
         * AUTH PROFILE:
         * - Sign in as the seeded John account.
         * - Explore existing boards and create board/list/card data.
         * - Keep Add member disabled to avoid adding John to his own board.
         */

        // --------------------------------------------------------------
        // Sign in
        // --------------------------------------------------------------
        Form signInForm = new Form();

        FormInput usernameInput = signInForm.inputField(
                FormInput.InputType.EMAIL,
                new Identification(
                        Identification.How.xpath,
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/MAIN[1]/FORM[1]/DIV[1]/INPUT[1]"));
        usernameInput.inputValues("john@phoenix-trello.com");

        FormInput passwordInput = signInForm.inputField(
                FormInput.InputType.PASSWORD,
                new Identification(
                        Identification.How.xpath,
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/MAIN[1]/FORM[1]/DIV[2]/INPUT[1]"));
        passwordInput.inputValues("12345678");

        inputSpecification.setValuesInForm(signInForm)
                .beforeClickElement("button")
                .withText("Sign in");

        // --------------------------------------------------------------
        // Board
        // --------------------------------------------------------------
        Form boardForm = new Form();

        FormInput boardNameInput = boardForm.inputField(
                FormInput.InputType.TEXT,
                new Identification(
                        Identification.How.id,
                        "board_name"));
        boardNameInput.inputValues(
                "TestCeption Board 1",
                "TestCeption Board 2",
                "TestCeption Board 3");

        inputSpecification.setValuesInForm(boardForm)
                .beforeClickElement("button")
                .withText("Create board");

        // --------------------------------------------------------------
        // Create list
        // --------------------------------------------------------------
        Form listForm = new Form();

        FormInput listNameInput = listForm.inputField(
                FormInput.InputType.TEXT,
                new Identification(
                        Identification.How.id,
                        "list_name"));
        listNameInput.inputValues(
                "RLM List 1",
                "RLM List 2",
                "RLM List 3");

        inputSpecification.setValuesInForm(listForm)
                .beforeClickElement("button")
                .withText("Save list");

        // --------------------------------------------------------------
        // Create card
        // --------------------------------------------------------------
        Form addNewCardForm = new Form();

        FormInput newCardInput = addNewCardForm.inputField(
                FormInput.InputType.TEXTAREA,
                new Identification(
                        Identification.How.id,
                        "card_name"));
        newCardInput.inputValues(
                "RLM Card 1",
                "RLM Card 2",
                "RLM Card 3");

        inputSpecification.setValuesInForm(addNewCardForm)
                .beforeClickElement("button")
                .withText("Add");

        // --------------------------------------------------------------
        // Edit card
        // --------------------------------------------------------------
        Form editCardForm = new Form();

        FormInput titleInput = editCardForm.inputField(
                FormInput.InputType.TEXT,
                new Identification(
                        Identification.How.xpath,
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/HEADER[1]/FORM[1]/INPUT[1]"));
        titleInput.inputValues("RLM Card Updated");

        FormInput descriptionInput = editCardForm.inputField(
                FormInput.InputType.TEXTAREA,
                new Identification(
                        Identification.How.xpath,
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/HEADER[1]/FORM[1]/TEXTAREA[1]"));
        descriptionInput.inputValues("RLM card description");

        inputSpecification.setValuesInForm(editCardForm)
                .beforeClickElement("button")
                .withText("Save card");

        // --------------------------------------------------------------
        // Card comment
        // --------------------------------------------------------------
        Form cardCommentForm = new Form();

        FormInput commentInput = cardCommentForm.inputField(
                FormInput.InputType.TEXTAREA,
                new Identification(
                        Identification.How.xpath,
                        "/HTML[1]/BODY[1]/MAIN[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]"
                                + "/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[1]"
                                + "/FORM[1]/DIV[2]/TEXTAREA[1]"));
        commentInput.inputValues("RLM test comment");

        inputSpecification.setValuesInForm(cardCommentForm)
                .beforeClickElement("button")
                .withText("Save comment");

        builder.crawlRules().setInputSpec(inputSpecification);

        builder.crawlRules().setDisableIdAndNameIdentification(true);

        /*
         * Prevent the same form from being submitted repeatedly while the
         * crawler remains in an equivalent state.
         */
        builder.setHandleSameFormInputsOncePerState(true);

        return builder;
    }

    @Override
    public SuiteGeneratorConfig getSuiteGeneratorConfig() {

        SuiteGeneratorConfig suiteGeneratorConfig = this.testSuiteGeneratorCommonConfig(url, waitTimeAfterReload);
        suiteGeneratorConfig.setScriptNameToInclude("application");
        suiteGeneratorConfig.setSourcemapURL("http://localhost:4000/js/application.js.map");
        suiteGeneratorConfig.setSrcCodeFolder("web/static/js");
        suiteGeneratorConfig.setFiredElementStrategy(false);

        return suiteGeneratorConfig;
    }

    @Override
    public DependencyGraphExtractionConfig getDependencyGraphExtractionConfig() {
        String dependencyGraphOptimized = "1 10 000 0011 00010 000000 0000000 00010000 101000010 0000001000 10010010000 000000000000 0000000000000 10000000000000 000000000010000 0000000000000000 01001011001100000 111000010000000000 0000000001001000000 10010000000000000000 000100001000100010000 1000000001000000000000 00010001000000000000000 001001100000000000000000 1011001100000000000000100 00000100000000000000000000 000010000000000000000000000 0000000101000000001000000000 11010100000000010000100000000 011000010000000010000000000000 0010111000100000000000100000001 01011100100000000000000000000001 111010001011000000100000000001000 0101000111000000000000000001000000 10100010000001000000100000100000000 011000110000010110100000000000000000 0000011100010000100000001000000000000 11010101001100100000101010101011000000 000001100010000000000001110001000000000 1010000000000000100010001000000000000000 01010001010100100000000000010000001000001 010000010100101000001010000000100000000000 0110010101111100101000000010000000000100000 00000010010001110000000000000000000000000000 100100000000001000000000000000000000000000000 0001000010000000010000000000000000000000000011 01011101010000000001000010101000000000000000011 010000000000000010000010010000000000000000000000 1000110000000011100010001100000100000000000000001 00001010000110001000000000000000000100000000000000 001000010100100010001000100000000000000000000000000 0010000000001100101000100000000000000000000000000010";

        DependencyGraphExtractionConfig dependencyGraphExtractionConfig = new DependencyGraphExtractionConfig();
        dependencyGraphExtractionConfig.setParetoFrontSolution(dependencyGraphOptimized);
        // window strategy
//        dependencyGraphExtractionConfig.setFixedMinimizedTestSuite("11101000101100100000100110000000000011000000000011000");
        // one by one strategy
        dependencyGraphExtractionConfig.setFixedSelectedTestSuite("11111111111111100000100110000000000011000000000011000");


        return dependencyGraphExtractionConfig;
    }
}
